### ISSUE TITLE
Allow modification of global ChartJS variables

### ISSUE THREAD

**Issue by devmattrick** [vmpowerio/chartjs-node#12] opened 2016-12-27 05:43 UTC
Hi there!

ChartJS has a number of [global variables](http://www.chartjs.org/docs/#chart-configuration-global-configuration) which would be very useful to be able to set so one doesn't have to set it for every chart they have created. It'd be very useful to have an (optional) way of passing these variables down to ChartJS.

Thanks for your time.

**Comment by FilipeDominguesGit** [comment] 2016-12-27 13:28
Hello! 

Maybe we could pass an options object on ChartjsNode constructor and assign it to the Chartjs.defaults.

ex:

```javascript
let options = {
  defaults:{
    global:{
        hover:{
            mode : 'whateverMode'
            }
        }
    }
};
var chartNode = new ChartjsNode(600, 600,options),
```
And then just assign it to Chartjs.defaults like this:

```javascript
 Object.assign(Chartjs.defaults,this._options.defaults);
```
Something like that? :smile:

**Comment by sedouard** [comment] 2016-12-27 15:36
This was one of the reasons I elected to make `Chart.js` a peerDependency. Since we are using the same module, if you do:

```js
Chartjs = require('chart.js')
Chartjs.defaults.global.hover.mode = 'nearest';
```

When `chartjs-node` requires Chart.js -- it should just pick up the changes, since the subsequent `require` on the module will just return same object. Does that not work out?

**Comment by sedouard** [comment] 2016-12-30 15:09
Gonna close this one out. @devmattrick go ahead and reopen if you think more needs to be done here.

**Comment by devmattrick** [comment] 2016-12-31 01:56
Sounds good. Wasn't aware that the subsequent require would return the same object. Obviously need to brush up a bit on my Node :P

**Comment by leighquince** [comment] 2017-02-15 15:57
for me this doesn't work out as when I require chart.js I get `ReferenceError: window is not defined`
at `chart.js/src/core/core.helpers.js:665`.

Seems like I need to require chart js within the jsdom env callback where window is available. Unless im doing something wrong?

Also thanks a lot for this as it's making server side rendering of charts soooo much easier.

**Comment by sedouard** [comment] 2017-02-15 16:58
Thanks for the feedback @leighquince glad to see it's helpful! 👍 

Do you mind pasting a code snippet that reproduces the error you mentioned?

**Comment by leighquince** [comment] 2017-02-15 17:22
it was just the inclussion of chart js that did it, version 2.5.0

`let Chartjs = require('chartjs')`

**Comment by sedouard** [comment] 2017-02-15 19:39
Ah - you're right. From my viewpoint this is an issue with this project since you can't load the chartjs module unless you pull in jsdom yourself -- which the point of this package is to avoid that.

I'll take a stab at a PR to take an options field which can set this as originally suggested by @FilipeDominguesGit

**Comment by SeanSobey** [comment] 2017-08-14 14:28
I also require access to the global chart instance, I need to change the defaults for the built in scales, however these default are not on the global object but need to be changed by calling `Chart.scaleService.updateScaleDefaults()`.

There are also a few other Chart properties that may be useful in future, such as `Chart.layoutService`, `Chart.helpers`, etc. Maybe providing a callback with access to the global chart would be more flexible?

```js
var chartNode = new ChartjsNode(600, 600, function(Chart) {
    Chart.defaults.global.hover.mode = 'whatevermode';
});
```

Then in index.js
```js
class ChartjsNode {
    constructor(width, height, onInit) {
        this._width = width;
        this._height = height;
        this._onInit = onInit;
    }
   ...
   const Chartjs = require('chart.js');
   if(this._onInit) {
        this._onInit(Chartjs );
    }
```

Of course this would also provide an alternative to the current plugins and charts options...

**Comment by sedouard** [comment] 2017-08-14 14:53
Yeah seems like a good idea so that this library doesn't have to chase around Chart.js features. I'm not a fan of callbacks in constructors.  Instead how about emitting an event.

```js
let chartNode = new ChartjsNode(600, 600);
chartNode.on('beforeDraw', Chartjs => {// do whatever; });
chartNode.drawChart(configuration);
```

We can make `ChartjsNode` an `EventEmitter`. In the future if anything else (synchronous) needs to be done within the jsdom environment, we can add event hooks.

I think my only concern is that would someone ever want to do something asynchronous within the jsdom environment? My thought is that anything asynchrounous required for the chart can be done before the `drawChart` call.

**Comment by SeanSobey** [comment] 2017-08-15 09:41
Yes the event route seems a better approach. I can't think of anything someone would need to do asynchronously, at least with the ChartJS global so I think the event implementation will be pretty robust that way.

I have implemented this in my [fork](https://github.com/SeanSobey/chartjs-node#global-chart-reference), along with tests and docs. I will implement and test the usage in my application, it should be ready for a pull request soon.

This feature does also make the plugin and chart configuration options redundant, since they can be done on the ChartJS instance, would you want to mark them as deprecated?

**Comment by SeanSobey** [comment] 2017-09-20 15:31
FYI, my [pull request](https://github.com/vmpowerio/chartjs-node/pull/37) for this feature has been merged. Documentation for how to use has been added to the Readme as well.

**Closed** 2017-09-20 17:12 UTC
Labels: enhancement, help wanted
